// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsPermissionPlusApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashPermissionPlusApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsPermissionPlusApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsPermissionPlusApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsPermissionPlusApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsPermissionPlusApi(lhsKey, rhsKey) {
          if deepEqualsPermissionPlusApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsPermissionPlusApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashPermissionPlusApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashPermissionPlusApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashPermissionPlusApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashPermissionPlusApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashPermissionPlusApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashPermissionPlusApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Mirror of `PermissionType` from `permission_plus_platform_interface`.
enum PermissionTypeMessage: Int {
  case camera = 0
  case microphone = 1
  case photos = 2
  case photosAddOnly = 3
  case location = 4
  case locationAlways = 5
  case locationWhenInUse = 6
  case notification = 7
  case contacts = 8
  case contactsReadOnly = 9
  case contactsWriteOnly = 10
  case calendar = 11
  case calendarReadOnly = 12
  case calendarWriteOnly = 13
  case reminders = 14
  case storage = 15
  case storageReadOnly = 16
  case storageWriteOnly = 17
  case bluetooth = 18
  case speech = 19
  case mediaLibrary = 20
  case sensors = 21
  case phone = 22
  case sms = 23
  case appTrackingTransparency = 24
  case criticalAlerts = 25
  case videos = 26
  case audio = 27
}

/// Mirror of `PermissionStatus` from `permission_plus_platform_interface`.
enum PermissionStatusMessage: Int {
  case notDetermined = 0
  case granted = 1
  case denied = 2
  case permanentlyDenied = 3
  case restricted = 4
  case limited = 5
  case provisional = 6
}

/// Mirror of `LocationAccuracy` from `permission_plus_platform_interface`.
enum LocationAccuracyMessage: Int {
  case reduced = 0
  case precise = 1
}

/// Represents a single entry in a permission → status map.
///
/// Used for returning results from [requestPermissions], since Pigeon
/// does not support `Map` with enum keys directly.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PermissionStatusMapEntry: Hashable {
  var permission: PermissionTypeMessage
  var status: PermissionStatusMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PermissionStatusMapEntry? {
    let permission = pigeonVar_list[0] as! PermissionTypeMessage
    let status = pigeonVar_list[1] as! PermissionStatusMessage

    return PermissionStatusMapEntry(
      permission: permission,
      status: status
    )
  }
  func toList() -> [Any?] {
    return [
      permission,
      status,
    ]
  }
  static func == (lhs: PermissionStatusMapEntry, rhs: PermissionStatusMapEntry) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPermissionPlusApi(lhs.permission, rhs.permission) && deepEqualsPermissionPlusApi(lhs.status, rhs.status)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PermissionStatusMapEntry")
    deepHashPermissionPlusApi(value: permission, hasher: &hasher)
    deepHashPermissionPlusApi(value: status, hasher: &hasher)
  }
}

private class PermissionPlusApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PermissionTypeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PermissionStatusMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return LocationAccuracyMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return PermissionStatusMapEntry.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PermissionPlusApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PermissionTypeMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PermissionStatusMessage {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? LocationAccuracyMessage {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? PermissionStatusMapEntry {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PermissionPlusApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PermissionPlusApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PermissionPlusApiPigeonCodecWriter(data: data)
  }
}

class PermissionPlusApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PermissionPlusApiPigeonCodec(readerWriter: PermissionPlusApiPigeonCodecReaderWriter())
}


/// Host API implemented in Swift, called from Dart.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PermissionPlusHostApi {
  /// Checks the current status of [permission] without triggering a request.
  func checkPermission(permission: PermissionTypeMessage, completion: @escaping (Result<PermissionStatusMessage, Error>) -> Void)
  /// Requests [permission] from the user.
  func requestPermission(permission: PermissionTypeMessage, completion: @escaping (Result<PermissionStatusMessage, Error>) -> Void)
  /// Requests multiple [permissions] at once.
  func requestPermissions(permissions: [PermissionTypeMessage], completion: @escaping (Result<[PermissionStatusMapEntry], Error>) -> Void)
  /// Opens the platform's app settings page.
  func openSettings(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Whether the platform recommends showing a rationale before requesting
  /// [permission].
  ///
  /// Always returns `false` on Apple platforms.
  func shouldShowRationale(permission: PermissionTypeMessage, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Gets the current location accuracy level.
  func getLocationAccuracy(completion: @escaping (Result<LocationAccuracyMessage, Error>) -> Void)
  /// Requests temporary precise location access (iOS 14+ only).
  ///
  /// [purposeKey] must match a key in the app's
  /// `NSLocationTemporaryUsageDescriptionDictionary` Info.plist entry.
  func requestTemporaryPreciseLocation(purposeKey: String, completion: @escaping (Result<PermissionStatusMessage, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PermissionPlusHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PermissionPlusApiPigeonCodec.shared }
  /// Sets up an instance of `PermissionPlusHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PermissionPlusHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Checks the current status of [permission] without triggering a request.
    let checkPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permission_plus_apple.PermissionPlusHostApi.checkPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkPermissionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let permissionArg = args[0] as! PermissionTypeMessage
        api.checkPermission(permission: permissionArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkPermissionChannel.setMessageHandler(nil)
    }
    /// Requests [permission] from the user.
    let requestPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permission_plus_apple.PermissionPlusHostApi.requestPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let permissionArg = args[0] as! PermissionTypeMessage
        api.requestPermission(permission: permissionArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionChannel.setMessageHandler(nil)
    }
    /// Requests multiple [permissions] at once.
    let requestPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permission_plus_apple.PermissionPlusHostApi.requestPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let permissionsArg = args[0] as! [PermissionTypeMessage]
        api.requestPermissions(permissions: permissionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionsChannel.setMessageHandler(nil)
    }
    /// Opens the platform's app settings page.
    let openSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permission_plus_apple.PermissionPlusHostApi.openSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openSettingsChannel.setMessageHandler { _, reply in
        api.openSettings { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openSettingsChannel.setMessageHandler(nil)
    }
    /// Whether the platform recommends showing a rationale before requesting
    /// [permission].
    ///
    /// Always returns `false` on Apple platforms.
    let shouldShowRationaleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permission_plus_apple.PermissionPlusHostApi.shouldShowRationale\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      shouldShowRationaleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let permissionArg = args[0] as! PermissionTypeMessage
        api.shouldShowRationale(permission: permissionArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      shouldShowRationaleChannel.setMessageHandler(nil)
    }
    /// Gets the current location accuracy level.
    let getLocationAccuracyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permission_plus_apple.PermissionPlusHostApi.getLocationAccuracy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getLocationAccuracyChannel.setMessageHandler { _, reply in
        api.getLocationAccuracy { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getLocationAccuracyChannel.setMessageHandler(nil)
    }
    /// Requests temporary precise location access (iOS 14+ only).
    ///
    /// [purposeKey] must match a key in the app's
    /// `NSLocationTemporaryUsageDescriptionDictionary` Info.plist entry.
    let requestTemporaryPreciseLocationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.permission_plus_apple.PermissionPlusHostApi.requestTemporaryPreciseLocation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestTemporaryPreciseLocationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let purposeKeyArg = args[0] as! String
        api.requestTemporaryPreciseLocation(purposeKey: purposeKeyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestTemporaryPreciseLocationChannel.setMessageHandler(nil)
    }
  }
}
